version: "3"
services:
  space:
    build: .
    restart: always
    container_name: prod_space
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  nginx:
    image: nginx:stable-alpine
    depends_on:
      - space
    container_name: prod_nginx
    volumes:
      - ./.docker/nginx:/etc/nginx/conf.d
      - ./.docker/nginx/certs:/etc/nginx/certs
    ports:
      - "80:80"
      - "443:443"