import type { Metadata } from 'next'
import './globals.css'
import StoreProvider from "@/app/_components/StoreProvider";




export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <StoreProvider>
        <html lang="en">
          <body className="w-screen h-screen">{children}</body>
        </html>
      </StoreProvider>
  )
}
